-- MySQL Script generated by MySQL Workbench
-- 01/02/17 19:16:24
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`userCharacter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`userCharacter` (
  `userCharacterID` INT NOT NULL AUTO_INCREMENT,
  `characterName` VARCHAR(45) NOT NULL DEFAULT 'character_name',
  `characterHP` INT NULL DEFAULT 10,
  `characterMana` INT NULL DEFAULT 10,
  `characterGold` INT NULL DEFAULT 0,
  `characterLvl` INT NULL DEFAULT 1,
  `characterAtc` INT NULL DEFAULT 1,
  `characterExp` INT NULL DEFAULT 0,
  PRIMARY KEY (`userCharacterID`),
  UNIQUE INDEX `userCharacterID_UNIQUE` (`userCharacterID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(45) NOT NULL DEFAULT 'user_name',
  `userPassword` VARCHAR(45) NOT NULL DEFAULT 'user_password',
  `email` VARCHAR(45) NOT NULL DEFAULT 'user_email',
  `characterID` INT NULL DEFAULT 0,
  PRIMARY KEY (`iduser`),
  INDEX `characterID_idx` (`characterID` ASC),
  UNIQUE INDEX `iduser_UNIQUE` (`iduser` ASC),
  CONSTRAINT `characterID`
    FOREIGN KEY (`characterID`)
    REFERENCES `mydb`.`userCharacter` (`userCharacterID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`monster`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`monster` (
  `monsterName` VARCHAR(45) NOT NULL DEFAULT 'monster',
  `goldLoot` INT NOT NULL DEFAULT 0,
  `expLoot` INT NOT NULL DEFAULT 0,
  `monsterHP` INT NULL DEFAULT 10,
  `monsterAtk` INT NULL DEFAULT 1,
  `monsterDef` INT NULL DEFAULT 1,
  `monsterID` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`monsterID`),
  UNIQUE INDEX `monsterID_UNIQUE` (`monsterID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`chest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`chest` (
  `chestID` INT NOT NULL AUTO_INCREMENT,
  `chestGold` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`chestID`),
  UNIQUE INDEX `chestID_UNIQUE` (`chestID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`eventReaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`eventReaction` (
  `eventReactionID` INT NOT NULL AUTO_INCREMENT,
  `reactionDescription` VARCHAR(45) NOT NULL DEFAULT 'link_to_description',
  PRIMARY KEY (`eventReactionID`),
  UNIQUE INDEX `eventReactionID_UNIQUE` (`eventReactionID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`event` (
  `eventID` INT NOT NULL AUTO_INCREMENT,
  `eventName` VARCHAR(45) NOT NULL DEFAULT 'eventname',
  `eventDescription` VARCHAR(45) NOT NULL DEFAULT 'link_to_description' COMMENT 'przechowuje link do opisu tekstowego',
  `eventReactionID` INT NULL DEFAULT 0,
  PRIMARY KEY (`eventID`),
  INDEX `eventReactionID` (`eventReactionID` ASC),
  UNIQUE INDEX `eventID_UNIQUE` (`eventID` ASC),
  CONSTRAINT `eventReactionID`
    FOREIGN KEY (`eventReactionID`)
    REFERENCES `mydb`.`eventReaction` (`eventReactionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


GRANT ALL ON `mydb`.* TO 'admin';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
